---
title: "SOC 280 Final Project"
author: "J Steven Raquel"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sna)
library(igraph)
library(epimdr)
library(pvclust)
library(CINNA)
data(gonnet)
```

# Abstract

# Introduction

# Methods

# Results

## Data Analysis

### Centrality

### Network Density

### K-cores

### Community Detection

```{r data-prep}
# data is loaded as 'gonnet'
nodes <- rownames(gonnet)
colnames(gonnet) <- nodes

gonnet_df <- data.frame(nodes) %>%
  mutate(gender = ifelse(grepl("m", nodes), yes = "m", no = NA)) %>%
  mutate(gender = ifelse(grepl("f", nodes), yes = "f", no = gender)) %>%
  mutate(gender_lty = ifelse(gender == "m", yes = 4, no = 3)) %>%
  mutate(gender_lty = ifelse(gender == "f", yes = 3, no = gender_lty)) %>%
  mutate(gender_lty = ifelse(gender %in% c("m", "f"), yes = gender_lty, no = 50)
         ) %>%
  mutate(attended_bar = gonnet["b",] == 1) %>%
  mutate(col = ifelse(attended_bar == T, "tomato1", "grey"))


gonnet_df$col[!(gonnet_df$gender %in% c("m", "f"))] <- "blue"
gonnet_df$col[gonnet_df$nodes == "b"] <- "tomato1"
```

```{r sociogram}
par(mfrow = c(1,1))
set.seed(10)
org_coord <- 
  gplot(gonnet, vertex.col = gonnet_df$col,
      vertex.sides = gonnet_df$gender_lty,
      # displaylabels = T, label.cex = 0.6, label.pos = 2,
      boxed.labels = F, pad = 2, 
      vertex.cex = 1.25)
# legend for gender
legend("topleft",
       legend = c("yes", "no"),
       col = c("tomato1", "grey"),
       fill = F, border = "white", pch = 19,
       title = "Bar Attendance", bty = "n")
legend("topright",
       legend = c("m", "f"),
       col = c("black"),
       fill = F, border = "white", pch = c(0, 2),
       title = "Gender", bty = "n")
# legend for bar attendance
title("Gonorrhea network, shaded by bar attendance")

```

```{r centrality}
cen <- get_centralities(gonnet, "directed")

# correlations between centrality measures
centrality_correlations(gonnet, cen)

# creating igraph object
gonnet_ig <- graph_from_adjacency_matrix(gonnet)

pc <- proper_centralities(gonnet_ig)

centralities <- calculate_centralities(gonnet_ig, 
                       include = pc[c(1, 4, 11, 16, 27, 
                                      45, 8, 18, 31, 43, 3, 19)])

# plot of different centralities' contributions via PCA
pca_centralities(centralities)

```

```{r male-female-outdegree}
gonnet_df2 <- cbind(gonnet_df, cen) %>% select(-id)

outdegree_gender <- gonnet_df2 %>% 
  select(nodes, gender, outdegree) %>% 
  drop_na()

# average outdegree overall
mean(outdegree_gender$outdegree)

# average outdegree among men
outdegree_male <- 
  outdegree_gender %>% 
  filter(gender == "m") %>% 
  select(nodes, outdegree)
outdegree_male$outdegree %>% mean()

# male outdegree that excludes nodes with zero outdegree
outdegree_male_dropzero <- 
  outdegree_male %>%
  filter(outdegree != 0)
outdegree_male_dropzero$outdegree %>% mean()

# average outdegree among females
outdegree_female <- 
  outdegree_gender %>%
  filter(gender == "f") %>% 
  select(nodes, outdegree) 
outdegree_female$outdegree %>% mean()

outdegree_female_dropzero <-
  outdegree_female %>%
  filter(outdegree != 0)
outdegree_female_dropzero$outdegree %>% mean()

# Student's t-test comparing the mean outdegree of men and women
t.test(x = outdegree_male$outdegree, 
       y = outdegree_female$outdegree,
       var.equal = TRUE)
```

```{r bar-attendance-outdegree}
outdegree_bar <- gonnet_df2 %>%
  select(nodes, attended_bar, outdegree)

# average outdegree among bar attendees
outdegree_bar %>% 
  filter(attended_bar == TRUE) %>%
  select(outdegree) %>% unlist() %>% mean()

# average outdegree among non-bar attendees
outdegree_bar %>% 
  filter(attended_bar == FALSE) %>%
  select(outdegree) %>% unlist() %>% mean()


```


```{r simulations}
# simulating similar networks and determining whether than outdegree is statistically significant
mc_sim(gonnet, n = 1000, alpha = 0.05, "three-cycle")

```


```{r gplot-outdegree}
# normalizing the outdegree of bar because of course it has a high outdegree
outdegree_m <- cen$outdegree + 1
outdegree_m[1] <- 1

set.seed(10)
gplot(gonnet, 
      vertex.col = gonnet_df$col,
      vertex.sides = gonnet_df$gender_lty,
      vertex.cex = outdegree_m,
      coord = org_coord)
# legend for gender
legend("topleft",
       legend = c("yes", "no"),
       col = c("tomato1", "grey"),
       fill = F, border = "white", pch = 19,
       title = "Bar Attendance", bty = "n")
legend("topright",
       legend = c("m", "f"),
       col = c("black"),
       fill = F, border = "white", pch = c(0, 2),
       title = "Gender", bty = "n")
title("Gonorrhea network, sized by outdegree")
```


## Principal Component Analysis

```{r gplot- centralities}
# extracting the centralities that were important based on the PCA
centrality_eigen <- centralities$`eigenvector centralities`
centrality_load <- centralities$`Load Centrality`
centrality_degree <- centralities$`Degree Centrality`
centrality_geodesic <- centralities$`Geodesic K-Path Centrality`
centrality_shortest <- centralities$`Shortest-Paths Betweenness Centrality`
```

```{r gplot-size-eigenvector-centrality}
set.seed(10)
gplot(gonnet, vertex.col = gonnet_df$col,
      vertex.sides = gonnet_df$gender_lty,
      vertex.cex = centrality_degree,
      # displaylabels = T, label.cex = 0.6, label.pos = 2,
      boxed.labels = F, pad = 2)



```


```{r density-based clustering}
par(mfrow = c(1,1))
clust <- hclust(dist(gonnet), method = "complete")
# clust <- equiv.clust(gonnet)

plot(clust)
bm_complete <- blockmodel(gonnet,
                          ec = clust, k = 15)

bmR_complete <- reorder_blockmodel(bm_complete)
# overall network density, which we will use for alpha
alpha <- bmR_complete$block.model %>% mean(na.rm = T)
paste0("The mean overall network density is ", round(alpha, 3), ".")

density_matrix <- bmR_complete$block.model
# plotting blockmodel 
gplot(density_matrix > alpha,
      diag = T,
      vertex.cex = 1.5,
      label = unique(bmR_complete$block.membership),
      # boxed.labels=F,
      vertex.col="grey",
      pad = 1.25)
title("Block sociogram")

```



```{r p-value-hierarchical-clustering, cache = T}
fit <- 
  pvclust(gonnet, 
  method.hclust = "single",
  method.dist = "euclidean",
  iseed = 10, # to get same results
  parallel = T, # to use all but one CPU thread
  nboot = 1000) 
```
```{r plot-dendrogram}
par(mfrow = c(1,1))
plot(fit)
pvrect(fit, alpha = 0.95)
```

```{r blockmodel}
set.seed(10)
# if pchisq > 0.05, cluster is significant
pp <- pvpick(fit)
# number of significant clusters
ideal_k <- pp$clusters %>% length()


# blockmodel using k = 58 and cutting trees at 0.5
bm_complete <- blockmodel(gonnet,
                          ec = fit$hclust,
                          k = ideal_k+9, mode = "digraph")

bmR_complete <- reorder_blockmodel(bm_complete)
# overall network density, which we will use for alpha
alpha <- bmR_complete$block.model %>% mean(na.rm = T)
paste0("The mean overall network density is ", round(alpha, 3), ".")

density_matrix <- bmR_complete$block.model

par(mfrow = c(1,2))
# original plot, again
gplot(gonnet, vertex.col = gonnet_df$col,
      vertex.sides = gonnet_df$gender_lty,
      # displaylabels = T, label.cex = 0.6, label.pos = 2,
      boxed.labels = F, pad = 2, 
      vertex.cex = 1.25)
# legend for gender
legend("topleft",
       legend = c("yes", "no"),
       col = c("tomato1", "grey"),
       fill = F, border = "white", pch = 19,
       title = "Bar Attendance", bty = "n")
legend("topright",
       legend = c("m", "f"),
       col = c("black"),
       fill = F, border = "white", pch = c(0, 2),
       title = "Gender", bty = "n")
# legend for bar attendance
title("Network of gonorrhea transfer")

# plotting blockmodel 
gplot(density_matrix > alpha,
      diag = T,
      vertex.cex = 1.5,
      # label = unique(bmR_complete$block.membership),
      # boxed.labels=F,
      vertex.col="grey",
      pad = 1.25, 
      # coord = org_coord
      )
title("Block sociogram")

```



```{r plotting-fast-greedy-community}
par(mfrow = c(1,1))
set.seed(10)
par(mfrow = c(1,2))
# original plot, again
org_coord <- gplot(gonnet, vertex.col = gonnet_df$col,
      vertex.sides = gonnet_df$gender_lty,
      # displaylabels = T, label.cex = 0.6, label.pos = 2,
      boxed.labels = F, pad = 2, 
      vertex.cex = 1.25)
# legend for gender
legend("topleft",
       legend = c("yes", "no"),
       col = c("tomato1", "grey"),
       fill = F, border = "white", pch = 19,
       title = "Bar Attendance", bty = "n")
legend("topright",
       legend = c("m", "f"),
       col = c("black"),
       fill = F, border = "white", pch = c(0, 2),
       title = "Gender", bty = "n")

# fast and greedy community detection
plot_fastgreedy_cd(gonnet, layout = org_coord, legend = F)
# labeling only the original bar patrons
```


```{r kcores}
edgelist <- as.edgelist(gonnet, n = dim(gonnet)[1])
plot_kcores(edgelist, sym = T, mode = "digraph")
```
